### PR TITLE
`importer-rest-api-specs` - construct a unique constant name for `type`

### LINKED ISSUE #3725: `DataFactory` @ `2018-06-01` duplicate `type` constant defined in-line on nested models
When processing the models defined in files situated in the nested directory `entityTypes`
image

We hit the following error:
`finding nested items yet to be parsed: appending model: appending constants: conflicting constant "type" with different values. First: map[DatasetReference:DatasetReference]. Second: map[IntegrationRuntimeReference:IntegrationRuntimeReference]`

The issues in the data are these references:
https://github.com/Azure/azure-rest-api-specs/blob/0c2e0ff7acea901abb0d6714385546788c10d878/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/IntegrationRuntime.json#L606-L627

https://github.com/Azure/azure-rest-api-specs/blob/0c2e0ff7acea901abb0d6714385546788c10d878/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L6260-L6283

https://github.com/Azure/azure-rest-api-specs/blob/0c2e0ff7acea901abb0d6714385546788c10d878/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L5291-L5314

Swagger PR that fixes the definitions: https://github.com/Azure/azure-rest-api-specs/pull/28319

### PR DESCRIPTION
**Pull request by stephybun**
This PR updates the `MapConstant` function to take an additional optional argument called `modelName` which will be used to construct a unique constant name for constants named `type` that do not have a unique name defined by `x-ms-enum` in the swagger.

The approach is intentionally scoped to constants called `type` to prevent renames of constants that already have descriptive field names.

Closes #3725

### CODE REVIEW

File: tools/importer-rest-api-specs/components/parser/constants/interface.go [hunk 1]
```diff
@@ -44,6 +44,15 @@ func MapConstant(typeVal spec.StringOrArray, fieldName string, values []interfac
...
 		if featureflags.AllowConstantsWithoutXMSEnum {
 			logger.Debug(fmt.Sprintf("Field %q had an invalid `x-ms-enum`: %+v", fieldName, err))
+			// this attempts to construct a unique name for a constant out of the model name and field name
+			// to prevent duplicate definitions of constants, specifically constants called `type`
+			// of which there are several in data factory (#3725)
+			if strings.EqualFold(fieldName, "type") && modelName != nil {
+				constantPrefix := strings.TrimSuffix(*modelName, "Type")
+				constantName = constantPrefix + strings.Title(fieldName)
+				logger.Debug(fmt.Sprintf("Field %q renamed to %q", fieldName, constantName))
+			}
```
Comment (tombuildsstuff) [inline tools/importer-rest-api-specs/components/parser/constants/interface.go:54]: can we add a test covering this scenario?

**Review by tombuildsstuff — COMMENTED** [review]
We should add a test covering this scenario, in particular having two different fields named `type`? But this otherwlse LGTM 👍

**Review by tombuildsstuff — APPROVED** [review]
Forgot to hit approve in addition to my previous comments 👍

File: tools/importer-rest-api-specs/components/parser/testdata/constants_multiple_type_enums.json [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+  ],
+  "security": [],
+  "securityDefinitions": {},
+  "paths": {
+    "/animal": {
+      "get": {
+        "tags": [
+          "Animal"
+        ],
+        "operationId": "Animal_Test",
```
Comment (tombuildsstuff) [inline tools/importer-rest-api-specs/components/parser/testdata/constants_multiple_type_enums.json:26]:
```suggestion
          "Example"
        ],
        "operationId": "Example_Animal",
```

File: tools/importer-rest-api-specs/components/parser/testdata/constants_multiple_type_enums.json [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+          }
+        }
+      }
+    },
+    "/planet": {
+      "get": {
+        "tags": [
+          "Planet"
+        ],
+        "operationId": "Planet_Test",
```
Comment (tombuildsstuff) [inline tools/importer-rest-api-specs/components/parser/testdata/constants_multiple_type_enums.json:44]: (as above)

```suggestion
          "Example"
        ],
        "operationId": "Example_Planet",
```

File: tools/importer-rest-api-specs/components/parser/constants_test.go [hunk 4]
```diff
@@ -284,6 +284,96 @@ func TestParseConstantsIntegersInlinedAsIntsWithDisplayName(t *testing.T) {
...
+	actual, err := ParseSwaggerFileForTesting(t, "constants_multiple_type_enums.json")
+	if err != nil {
+		t.Fatalf("parsing: %+v", err)
+	}
+
+	expected := importerModels.AzureApiDefinition{
+		ServiceName: "Example",
+		ApiVersion:  "2020-01-01",
+		Resources: map[string]importerModels.AzureApiResource{
+			"Animal": {
```
Comment (tombuildsstuff) [inline tools/importer-rest-api-specs/components/parser/constants_test.go:297]: (as below) can we combine these into the same API Resource, so that we can ensure we're testing that we get unique names back within the same API Resource?

**Review by tombuildsstuff — COMMENTED** [review]
Do we need to have both of these Operations within the same Swagger Tag, so that these are parsed in the same API Resource to ensure this codepath is covered/the constant names are unique?

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍
